### ISSUE TITLE
FileNotFoundException when try to use clj-fast

### ISSUE THREAD

**Issue by newmen** [bsless/clj-fast#22]
Hi,

I'd added this library to the dependencies list in my leinengen project.clj file like:
```
:dependencies [; ...
               [bsless/clj-fast "0.0.9"]
               ; ...
               ]
```

And then I've started the repl and tried to use somethink from `README`, but got a error:

```
x.y.core=> (use '[clj-fast.collections.concurrent_hash_map :as chm])

Execution error (FileNotFoundException) at x.y.core/eval39551 (form-init17436836735770775491.clj:1).
Could not locate clj_fast/collections/concurrent_hash_map__init.class, clj_fast/collections/concurrent_hash_map.clj or clj_fast/collections/concurrent_hash_map.cljc on classpath. Please check that namespaces with dashes use underscores in the Clojure file name.
```

What I do wrong?

**Comment by bsless** [comment]
The only thing you did wrong was following a slightly outdated section of the README, the namespace was renamed to `clj-fast.collections.concurrent-map`
Please let me know if this solves the issue

**Comment by newmen** [comment]
Yep! That's works! Thanks :)
